### ISSUE TITLE
ensure_future asyncio issue in odin-control 1.2.0

### ISSUE THREAD

**Issue by josephnobes-stfc** [stfc-aeg/loki#32]
```python
Traceback (most recent call last):
  File "/usr/bin/odin_control", line 11, in <module>
    load_entry_point('odin-control==1.2.0', 'console_scripts', 'odin_control')()
  File "/usr/lib/python3.7/site-packages/odin/server.py", line 60, in main
    config.static_path, adapters)
  File "/usr/lib/python3.7/site-packages/odin/http/server.py", line 53, in __init__
    self.api_route.initialize_adapters()
  File "/usr/lib/python3.7/site-packages/odin/http/routes/api.py", line 182, in initialize_adapters
    run_async(initialize_method, self.adapters)
  File "/usr/lib/python3.7/site-packages/odin/async_util.py", line 55, in run_async
    result = loop.run_until_complete(func(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 562, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 619, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

**Comment by josephnobes-stfc** [comment]
Observed in build after including `odin-control` v1.2.0 at bcac7c03d00764cbc6378250e10d4794df636129. Crash prevents `odin-control` from running.

**Comment by josephnobes-stfc** [comment]
Issue has now been resolved.

**Comment by josephnobes-stfc** [comment]
Re-opening to allow PR #31 to close issue when merged.
